In [1]:
import numpy as np

In [2]:
np.array((2, 3, 4))

array([2, 3, 4])

In [4]:
np.array([(2.0, 3), (4, 5)])

array([[2., 3.],
       [4., 5.]])

In [8]:
np.array([(2.0, "three"), (4, 5)])

array([['2.0', 'three'],
       ['4', '5']], dtype='<U32')

In [7]:
np.random.random((2, 4))

array([[0.49310472, 0.50607959, 0.96872171, 0.51644162],
       [0.82804261, 0.22404051, 0.60511688, 0.01701397]])

In [9]:
np.arange(2, 3, .1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [10]:
np.arange(1, 20, 1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [11]:
np.linspace(1, 6, num = 10, endpoint = False)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [13]:
list(np.array((2, 3, 4))) # can cast the entire array to a data type

[2, 3, 4]

In [15]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = a1[2]
a2

3

In [21]:
a4 = np.array([[1, 2, 3], [4, 5, 6]])
a4[1, 2]

6

In [20]:
a4[1][1]

5

In [23]:
a1 = np.array([[1, 2, 3], [4, 5, 6]])
a2 = a1[0:2, 1:3]
a2

array([[2, 3],
       [5, 6]])

In [25]:
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a2 = a1[0:2, 1:3]
a2

array([[2, 3],
       [5, 6]])

In [27]:
a1 = np.array([[7, 0,  1,  1,  2],
               [7, 3,  5,  8,  13],
               [7, 21, 34, 55, 89],
               [7,  7,  7,  7,  7]])
a1[0:-1, 1:]

array([[ 0,  1,  1,  2],
       [ 3,  5,  8, 13],
       [21, 34, 55, 89]])

In [28]:
a1 * 4.0

array([[ 28.,   0.,   4.,   4.,   8.],
       [ 28.,  12.,  20.,  32.,  52.],
       [ 28.,  84., 136., 220., 356.],
       [ 28.,  28.,  28.,  28.,  28.]])

In [29]:
a2 = a1 * a1
a2

array([[  49,    0,    1,    1,    4],
       [  49,    9,   25,   64,  169],
       [  49,  441, 1156, 3025, 7921],
       [  49,   49,   49,   49,   49]])

In [31]:
a1 = np.array([[1,2,3,4,5],[3,3,4,1,2]])
a2 = a1[a1 > 2]
a2

array([3, 4, 5, 3, 3, 4])

In [33]:
a3 = a1 > 2
a3

array([[False, False,  True,  True,  True],
       [ True,  True,  True, False, False]])

In [38]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
(arr + arr)[1] # [8, 10, 12]

array([ 8, 10, 12])

In [35]:
arr[arr < 3][1] # 2

2

In [36]:
arr[arr*2 < 10] # [1, 2, 3, 4]

array([1, 2, 3, 4])

In [37]:
(arr + arr)[2:3] # [14, 16, 18]

array([[14, 16, 18]])