In [6]:
import numpy as np

In [7]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
(arr + arr)[1]

array([ 8, 10, 12])

In [8]:
(arr + arr)[2:3]

array([[14, 16, 18]])

In [11]:
arr = np.array([[1,9,8,9],[1,2,1,3]])
constr1 = arr > 5
constr2 = arr % 2 ==1
new_arr = arr[constr1 | constr2]
new_arr

array([1, 9, 8, 9, 1, 1, 3])

In [12]:
arr = np.array([1,1,2,3,5,8,13])
arr1 = np.where(arr % 3 == 0, 1, np.where(arr % 2 == 0 , 0, arr))
arr1

array([ 1,  1,  0,  1,  5,  0, 13])

In [16]:
arr = np.array([[3,  14, 15],
                [92, 65, 35]])
arr.sort(axis = 1)
arr

array([[ 3, 14, 15],
       [35, 65, 92]])

In [13]:
arr = np.array([[1, 3, 6, 7, 8], [3, 3, 3, 3, 6]])
print(arr.max(axis = 0))
print(type(arr.max(axis = 0)))

[3 3 6 7 8]
<class 'numpy.ndarray'>


In [17]:
arr = np.array([[1, 3, 6, 7, 8], [3, 3, 3, 3, 6]])
print(arr.sum(axis = 1))

[25 18]


In [29]:
arr = np.array([[1, 3, 6, 7, 8], [3, 3, 3, 3, 6]])
arr2 = arr
arr2[0] += 1
arr2

array([[2, 4, 7, 8, 9],
       [3, 3, 3, 3, 6]])

In [33]:
arr = np.arange(1,10,.5)
arr2 = np.linspace(1,5,num=10)
arr3 = np.random.random((3,4))
arr3.max()

0.9759479329546076

In [30]:
arr[arr % 2 == 0]

array([2, 4, 8, 6])

In [31]:
arr[(arr % 2 == 0) & (arr > 3)]

array([4, 8, 6])

In [32]:
arr2.resize(2, 5)
arr2

array([[2, 4, 7, 8, 9],
       [3, 3, 3, 3, 6]])